config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#signup'
  get 'pages/signup'
  get 'pages/contact'
  get 'pages/about'
  get 'pages/help'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def signup
    end
    
    def contact
    end
    
    def help
    end
    
    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  
  <link rel="stylesheet" href="https://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<!---------------------Header--------------------->
<div class="header">
  <div class="container">
    <a href="/"><img src="http://s3.amazonaws.com/codecademy-content/projects/pocketbook/logo.svg"></a>
  </div>
</div>

<%= yield %>

<!---------------------Footer--------------------->
<div class="footer">
  <div class="container">
    <%= link_to "Contact", pages_contact_path %>&emsp;
    <%= link_to "Help Center", pages_help_path %>&emsp;
    <%= link_to "About", pages_about_path %>
  </div>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <h1>About Pocketbook</h1>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <h1>Contact us</h1>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <h1>Help</h1>
    </div>
  </div>
</div>

app/views/pages/signup.html.erb
<!---------------------Main--------------------->
<div class="main">
  <div class="container">
    <h2>Join Pocketbook</h2>
    <form>
        <div class="form-group">
            <label>First name</label>
            <input class="form-control" type="text">
            
            <label>Last name</label>
            <input class="form-control" type="text">
            
            <label>Email</label>
            <input class="form-control" type="email">
            
            <label>Password</label>
            <input class="form-control" type="password">
        </div>
    </form>
    <a class="btn" href="#">Create account</a>
  </div>
</div>